spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/wc/board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: local
    include: secret